---
title: "About this site"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)

source(here::here("R/utils.R"))

library(tidyverse)

nys_date <- read_csv(here("data/by-county-cases-tests-nys.csv")) %>% 
  filter(date == max(date)) %>% 
  distinct(date) %>% 
  pull()

nyt_date <- read_csv(here("data/by-county-cases-deaths-nyt.csv")) %>%
  filter(date == max(date)) %>% 
  distinct(date) %>% 
  pull()

mun_date <- read_csv(here("data/by-mun-cases.csv")) %>% 
  filter(date == max(date)) %>% 
  distinct(date) %>% 
  pull()

hosp_date <- read_csv(here("data/hospital-beds-occupancy.csv")) %>% 
  filter(year_week == max(year_week)) %>% 
  distinct(year_week) %>% 
  pull()
```

This site contains information about the Covid-19 pandemic in Westchester County, NY and the surrounding metroplitan area. The [Westchester County Department of Health website](https://health.westchestergov.com/2019-novel-coronavirus) does not provide much data or detailed information about the state of the pandemic in the county, so this site hopes to fill the gap.

## Data sources


### [New York State Statewide Covid-19 Testing](https://health.data.ny.gov/Health/New-York-State-Statewide-COVID-19-Testing/xdss-u53e)

*New York State Department of Health*

This dataset includes the number of **tests** and **positive cases** of Covid-19 in New York State. The data is reported by county. It is updated daily and includes all tests reported by the end of the prior day. Tests include those administered by clinical laboratories as well as pooled or batch tests reported by colleges and universities.

Tests are assigned to a county based on the patient's address. If that cannot be determined, the address of the health care provider who ordered the test is used.

If a person has multiple specimens tested on the same day, they are only counted as one test. If a person is tested on multiple days, each day's test will be counted separately. An individual will only be counted positive one time, regardless of the number of positive tests that individual has.

Most recent data: **`r month_day_year(nys_date)`**
<br>
Update frequency: **Daily**
<br>
Geographic aggregation: **County (New York State only)**
<br>
Where it's used: **New and total tests, new and total cases, test positivity rate**

<br>
<br>

### [Coronavirus (Covid-19) Data in the United States](https://github.com/nytimes/covid-19-data)

*The New York Times*

This dataset includes the number of **cases** and **deaths** due to Covid-19 in the United States. The data is reported by county. It is updated daily and includes all cases and deaths compiled by *Times* journalists by the end of the prior day. The data is based on reports from state and local health agencies across the county and each state may have a slightly different reporting methodology.

For counties in New York State, the *Times* uses data reported by the NYS Department of Health. There is a one-day lag in the NYS data in the *Times* dataset. For example, data counted on December 16 by the New York Times was reported on December 15 by NYSDOH.

Beginning August 6, the [methodology for assigning deaths to counties in New York State was modified](https://github.com/nytimes/covid-19-data/blob/master/NEW-YORK-DEATHS-METHODOLOGY.md). Currently, deaths are assigned to the county of residence. Before August 6, deaths were assigned to county in which the death took place.

Most recent data: **`r month_day_year(nyt_date)`**
<br>
Update frequency: **Daily**
<br>
Geographic aggregation: **County (United States)**
<br>
Where it's used: **New and total deaths, new and total cases (metro area)**

<br>
<br>

### [Covid-19 Confirmed Cases](https://www.westchestergov.com/covid-19-cases)

*Westchester County Department of Health*

This dataset includes the number of Covid-19 **cases** in each of the 43 municipalities of Westchester County. It is updated on (most) weekdays and includes all cases in which a positive coronavirus test is associated with a confirmed address in Westchester County. With each update, the County posts the number of new cases, active cases, and total cases per municipality. The number of "active cases" refers the number of positive tests in the past two weeks. 

Often, the data reported by the county differs significantly from the data reported by NYSDOH. Given the lack of information shared by the Westchester County Department of Health about this data, I only use the County data to compare municipalities within Westchester. The data released by the County should not be directly compared to data released by the State or other sources.

Unfortunately, the County does not currently post historical data, but rather posts a map on most weekdays to the [WestchesterGov Twitter account](https://twitter.com/westchestergov/status/1336045976981811206). Because of this limitation, I have extracted this historical data from maps that are posted on Twitter. This extraction process is imperfect but until the county releases more accurate historical data, this is best I can do. Beginning on December 3, 2020, I began scraping the daily data from the [Westchester County website](https://westchestergov.com/covid-19-cases), which results in more reliable data. Because of the unavailability of this historical data from the County, *extreme caution* should be used when looking at municipal-level trends.

Given these limitations, I have decided to use the "active cases" metric as rolling 14-day average for most of the municipal-level on this site, as it seems to be the best balance between accuracy and recency If you or anyone you know works for the County, please encourage them to release more detailed historical data!

Most recent data: **`r month_day_year(mun_date)`**
<br>
Update frequency: **Weekdays (usually)**
<br>
Geographic aggregation: **Municipality (Westchester County only)**
<br>
Where it's used: **New and total cases**

<br>
<br>

### [COVID-19 Reported Patient Impact and Hospital Capacity by Facility](https://healthdata.gov/dataset/covid-19-reported-patient-impact-and-hospital-capacity-facility)

*United States Department of Health and Human Services*

This dataset includes **capacity** and **utilization** of hospitals in the United States. It is reported on a weekly basis and provides facility-level information such as the number of total inpatient and ICU beds, the number of inpatient and ICU beds currently occupied, and the number of Covid-19 patients currently admitted to each hospital facility.

The data is derived from reports made by hospitals and state health departments to HHS. It includes hospitals registered with the Centers for Medicare & Medicaid Services, but *does not* include psychiatric, rehabilitation, Indian Health Service (IHS) facilities, U.S. Department of Veterans Affairs (VA) facilities, Defense Health Agency (DHA) facilities, and religious non-medical facilities.

On this site, I use weekly average figures reported by the HHS dataset. In other words, this data is not a snapshot of hospital occupancy on a given day, but rather the average occupancy over the report week.

Hospital metric definitions:

- Covid-19 patients: patients currently hospitalized in an inpatient bed who have laboratory-confirmed or suspected Covid-19, including those in observation beds
- Total beds: staffed inpatient beds including all overflow and active surge/expansion beds used for inpatients (including all designated ICU beds)
- Beds used: staffed inpatient beds that are occupied
- Bed occupancy: beds used divided by total beds
- Total ICU beds: staffed inpatient ICU beds
- ICU beds used: staffed inpatient  ICU beds that are occupied
- Bed occupancy: ICU beds used divided by total ICU beds

Most recent data: **`r month_day_year(hosp_date)` -- `r month_day_year(hosp_date + 7)`**
<br>
Update frequency: **Weekly**
<br>
Geographic aggregation: **None (facility-level data, United States)**
<br>
Where it's used: **Hospital capacity, occupancy, Covid-19 patients**

## Me

This website was built and is maintained by me, [Matt Herman](http://mattherman.info). I live in Katonah, NY. Contact me at [mfherman@gmail.com](mailto:mfherman@gmail.com) with comments, questions, or suggestions.

## Tools, etc.

This website is built using the [Distill framework for R Markdown](https://rstudio.github.io/distill/). All data collection and aggregation is done using the [R programming language](https://www.r-project.org/). The interactive charts are made with [Plotly](https://plotly.com/), maps are made with [Leaflet](https://leafletjs.com/), and tables are made with [DataTables](https://datatables.net/). The static HTML is hosted by [GitHub Pages](https://pages.github.com/).

All source code for downloading and aggregating the data as well as building the website is available on [GitHub](https://github.com/mfherman/westchester-covid).